app/models/parking.rb, app/models/review.rb
Added association dependencies to parking and review model
=> dependency: :destroy

Gemfile.lock, db/seeds.rb
=> Added seeds without images

app/models/parking.rb, app/models/review.rb, db/seeds.rb
=> seeds done

Gemfile, Gemfile.lock, app/controllers/application_controller.rb
=> Installed pundit

Gemfile, Gemfile.lock, app/models/parking.rb, config/initializers/geocoder.rb
=> Installed geocoder

db/seeds.rb
=> Done cloudinary seeds

app/controllers/users_controller.rb, app/policies/application_policy.rb, app/policies/user_policy.rb, app/views/users/edit.html.erb, config/routes.rb, test/controllers/users_controller_test.rb, test/policies/user_policy_test.rb
=> User parking update

app/javascript/plugins/init_mapbox.js, app/views/layouts/application.html.erb, app/views/parkings/index.html.erb
Display route direction from current location to clicked destination
=> Created routing from point a to b

app/controllers/parkings_controller.rb, app/javascript/plugins/init_mapbox.js, app/views/parkings/_info_window.html.erb, app/views/parkings/index.html.erb
=> Added cards to parking index

app/javascript/plugins/init_mapbox.js, package.json, yarn.lock
=> Calculating distance between current location and destination

app/models/parking.rb, app/views/parkings/show.html.erb, app/views/reviews/_review.html.erb, db/seeds.rb
Added review seeds.
Added average rating to view
=> added seeds and average to parking view

app/assets/stylesheets/components/_cards.scss, app/javascript/packs/application.js, app/javascript/plugins/init_carousel.js, app/views/parkings/_info_window.html.erb, app/views/parkings/index.html.erb, config/webpack/environment.js, package.json, yarn.lock
=> Parkings index card

app/javascript/plugins/init_sweetalert.js, package.json, yarn.lock
Alert button will pop up when user's current location is 0.05km from destination (close #38)
=> Sweet alert

app/assets/stylesheets/components/_navbar.scss, app/javascript/packs/application.js, app/views/layouts/application.html.erb
fixed navbar to be fully stickied
=> fixed navbar to stay at bottom of page even when empty

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_index.scss, app/javascript/components/directionSync.js, app/javascript/packs/application.js, app/views/parkings/show.html.erb, app/views/reviews/_review.html.erb, app/views/shared/_banner.html.erb
=> Parkings show

app/assets/stylesheets/components/_marker.scss, app/assets/stylesheets/config/_colors.scss, app/javascript/components/directionSync.js, app/javascript/plugins/init_carousel.js
=> bouncing JS

app/assets/stylesheets/components/_cards.scss, app/views/parkings/_average_rating.html.erb, app/views/parkings/_review_pluralize.html.erb, app/views/parkings/show.html.erb, app/views/reviews/_review.html.erb
=> Show carousel

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_buttons.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
=> Landing page

app/assets/stylesheets/components/_banner.scss
=> Made the text next to logo white

app/controllers/parkings_controller.rb
Close #47 
Directions connected from show to index. Will need to maybe add an event listener to select the active card/marker once the page is loaded? I will take a look, but may need your help🙏
=> connected directions from show to index

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_map.scss, app/controllers/parkings_controller.rb, app/javascript/plugins/init_mapbox.js, app/views/parkings/_info_window.html.erb, app/views/parkings/index.html.erb
closes #63 
removed info window card
=> Parking index css

app/javascript/packs/application.js, app/javascript/plugins/init_directionsync.js, app/javascript/plugins/init_getid.js, app/javascript/plugins/init_pinmarker.js, app/javascript/plugins/init_route.js
=> Changed js file names

app/models/parking.rb, app/views/parkings/show.html.erb
=> added description to show

app/javascript/plugins/init_carousel.js, app/views/parkings/_review_pluralize.html.erb, app/views/parkings/index.html.erb
=> Parkings index cards

app/assets/stylesheets/components/_banner.scss, app/views/pages/home.html.erb
=> Fixed homepage title

db/seeds.rb
Just added better reviews and more users
=> added a couple more user seeds

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_cards.scss, app/javascript/plugins/init_carousel.js, app/views/parkings/_review_pluralize.html.erb, app/views/parkings/index.html.erb, app/views/parkings/show.html.erb
=> Changed css styles on parking show

app/views/parkings/index.html.erb
=> Changed the layout for rating & review

app/views/parkings/index.html.erb
=> Removed whitespace after parking review

app/views/parkings/index.html.erb
=> Resized map height

app/views/parkings/index.html.erb
=> Resized the map

app/controllers/reviews_controller.rb, app/models/review.rb, db/migrate/20210607015256_add_risk_level_to_reviews.rb, db/schema.rb, test/controllers/reviews_controller_test.rb
=> Add risk level to review model

app/assets/stylesheets/components/_buttons.scss, app/controllers/parkings_controller.rb, app/controllers/reviews_controller.rb, app/policies/review_policy.rb, app/views/parkings/show.html.erb, app/views/reviews/_form.html.erb, app/views/reviews/_modal.html.erb, test/policies/review_policy_test.rb
=> Added review controller & view

app/assets/stylesheets/components/_marker.scss, app/views/parkings/_marker.html.erb
=> Created free parking marker in yellow & black

app/assets/stylesheets/components/_marker.scss, app/assets/stylesheets/config/_colors.scss, app/views/parkings/_marker.html.erb
=> Changed marker color

app/policies/reply_policy.rb, test/policies/reply_policy_test.rb
=> Added reply policy

app/controllers/reviews_controller.rb, app/views/reviews/_form.html.erb
=> Fixed review

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/views/parkings/_new_form.html.erb
=> added style to create form

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_cards.scss, app/javascript/plugins/init_carousel.js, app/views/parkings/index.html.erb
=> Added indicator to carousel & resized the map

app/views/parkings/_review_carousel.html.erb
=> Added indicator to parking show review

app/javascript/plugins/init_pinmarker.js, app/models/parking.rb
=> Solved bug create location

app/views/reviews/_form.html.erb, app/views/reviews/_modal.html.erb
added padding, aligned buttons and changed text
=> made changes to review form

app/views/parkings/show.html.erb
=> fixed alignment for show info

app/assets/stylesheets/components/_banner.scss, app/views/pages/home.html.erb
=> added more left-side margin

app/models/parking.rb, app/views/parkings/index.html.erb
=> Parkings card fix

app/javascript/plugins/init_mapbox.js, app/javascript/plugins/init_route.js, app/javascript/plugins/init_syncCardMarker.js
=> Adding condition to map

Gemfile, Gemfile.lock, app/assets/stylesheets/components/_buttons.scss, app/controllers/parkings_controller.rb, app/models/favorite.rb, app/models/parking.rb, app/models/user.rb, app/policies/parking_policy.rb, app/views/pages/home.html.erb, app/views/parkings/_like_button.html.erb, app/views/parkings/index.html.erb, app/views/parkings/show.html.erb, app/views/parkings/toggle_favorite.js.erb, config/initializers/acts_as_favoritor.rb, config/routes.rb, db/migrate/20210608015630_acts_as_favoritor_migration.rb, db/schema.rb
=> Parkings index

app/assets/stylesheets/components/_cards.scss, app/views/parkings/_review_carousel.html.erb
=> Fixed carousel display

app/views/parkings/show.html.erb, app/views/reviews/_modal.html.erb
=> Fixed parking show buttons

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_icons.scss, app/assets/stylesheets/components/_risk_meter.scss, app/javascript/plugins/init_carousel.js, app/views/parkings/_average_rating.html.erb, app/views/parkings/index.html.erb, app/views/parkings/show.html.erb
=> Fixed parkings cards index and show

app/javascript/plugins/init_carousel.js, app/views/parkings/_average_rating.html.erb, app/views/parkings/index.html.erb, db/seeds.rb
Pushing the corrections we did today for the risk marker
=> Corrections

app/controllers/notifications_controller.rb, app/models/notification.rb, app/models/parking.rb, app/models/review.rb, app/policies/notification_policy.rb, app/views/notifications/index.html.erb, config/routes.rb, db/migrate/20210609021315_create_notifications.rb, db/schema.rb, test/controllers/notifications_controller_test.rb, test/models/notification_test.rb, test/policies/notification_policy_test.rb
Set up logic to update notification page when a new review drops the safety level of a favorited parking spot to below 40%
=> Notification setup

app/views/pages/home.html.erb
changed homepage logo to be consistent with navbar
=> changed homepage logo to be consistent with navbar

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_icons.scss, app/assets/stylesheets/components/_risk_meter.scss, app/assets/stylesheets/config/_colors.scss, app/views/parkings/_average_rating.html.erb, app/views/parkings/_review_pluralize.html.erb, app/views/parkings/index.html.erb, app/views/parkings/show.html.erb
=> Parking card design

app/views/parkings/index.html.erb
=> fixed map view height

app/assets/stylesheets/config/_colors.scss
=> changed default blue color

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_notification.scss, app/controllers/notifications_controller.rb, app/models/review.rb, app/models/user.rb, app/policies/notification_policy.rb, app/views/notifications/index.html.erb, app/views/shared/_navbar.html.erb, db/migrate/20210609071106_add_user_to_notifications.rb, db/schema.rb
=> Notification badge

app/views/shared/_navbar.html.erb
=> added yellow to notifications

app/assets/stylesheets/components/_cards.scss, app/views/parkings/index.html.erb
=> Parking card index fix

app/assets/stylesheets/components/_body.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb
=> made body fixed

app/assets/stylesheets/components/_navbar.scss
=> increased navbar height by 1vh

public/404.html, public/500.html
=> Added error pages

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_navbar.scss, app/views/parkings/index.html.erb
made navbar bigger and aligned cards and map to fit due to this
=> made navbar bigger and aligned cards and map to fit due to this

app/assets/stylesheets/components/_icons.scss, app/assets/stylesheets/config/_colors.scss, app/views/parkings/index.html.erb
=> Removed number fixed button color

app/assets/stylesheets/components/_cards.scss, app/controllers/notifications_controller.rb, app/views/notifications/index.html.erb
=> Notifications view css

app/assets/stylesheets/components/_cards.scss, app/views/parkings/_review_carousel.html.erb
=> fixed margin on review cards

app/javascript/plugins/init_mapbox.js, app/javascript/plugins/init_route.js
=> Map zoom out to show whole route

app/assets/stylesheets/components/_risk_meter.scss
=> Fixed gauge meter

app/assets/stylesheets/components/_cards.scss
=> Resized button

app/views/shared/_navbar.html.erb
Reverts josem-gp/baiku-app#252
=> Revert "added color to navbar for profile"

app/assets/stylesheets/components/_icons.scss, app/views/parkings/show.html.erb
=> Enlarged like icon

app/assets/stylesheets/components/_icons.scss, app/views/parkings/_review_carousel.html.erb, app/views/parkings/show.html.erb
=> Bold reviewer name

app/assets/stylesheets/components/_buttons.scss, app/views/parkings/_new_form.html.erb, app/views/reviews/_form.html.erb
Add a parking spot
Add a review
=> Added padding to buttons

app/assets/stylesheets/components/_buttons.scss, app/views/parkings/_new_form.html.erb, app/views/reviews/_form.html.erb
Search button
Review buttons
Add a new spot buttons
=> Fixed button margin

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_risk_meter.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/parkings/_new_form.html.erb, app/views/parkings/index.html.erb
=> Signup form - design

app/assets/stylesheets/components/_buttons.scss, app/views/parkings/_new_form.html.erb, app/views/reviews/_form.html.erb
=> Remained the original button class

app/assets/stylesheets/components/_banner.scss
=> made home banner responsive in desktop view

app/assets/stylesheets/components/_banner.scss, app/views/pages/home.html.erb
=> cleaned up banner css page and made text responsive across all devices

app/assets/stylesheets/components/_banner.scss, app/views/shared/_banner.html.erb
=> fixed banner missing from studios css

app/assets/stylesheets/components/_buttons.scss, app/views/parkings/_new_form.html.erb
=> made buttons responsive across larger devices

app/assets/stylesheets/components/_form.scss
=> made form page responsive

app/assets/stylesheets/components/_navbar.scss
=> fixed overlapping navbar issue

app/assets/stylesheets/components/_map.scss, app/views/parkings/index.html.erb
=> fixed map alignment with carousel

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_icons.scss, app/assets/stylesheets/config/_colors.scss, app/views/parkings/_like_button.html.erb, app/views/parkings/index.html.erb, app/views/parkings/show.html.erb, app/views/shared/_banner.html.erb
=> changed heart from absolute to relative position for responsiveness

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/config/_colors.scss, app/views/pages/home.html.erb
fixed logo responsiveness on home
=> fixed home responsiveness

app/assets/stylesheets/components/_navbar.scss
=> fixing viewport
